/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;

import Utilitaries.MetodoCategorias;
import Utilitaries.MetodoMarcas;
import Utilitaries.MetodoProducto;
import java.awt.event.KeyEvent;

/**
 *
 * @author Paul
 */
public class BuscarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProducto
     */
    private String Buscado = "";
    private int indexInsertar = 0;
    private int frmAIndexar;
    public BuscarProducto() {
        initComponents();
        BuscarCargarTabla();
        CargarCmb();
    }
    private void CargarCmb(){
        String[] Marcas = MetodoMarcas.BuscarMarcasString("");
        String[] SubCategoria = MetodoCategorias.TodasSubCategorias("");
        cmbMarca.removeAllItems();
        cmbSubCategoria.removeAllItems();
        cmbMarca.addItem("NINGUNO");
        cmbSubCategoria.addItem("NINGUNO");
        for(String item : Marcas){
            cmbMarca.addItem(item);
        }
        for(String item : SubCategoria){
            cmbSubCategoria.addItem(item);
        }
    }
    public void BuscarCargarTabla(){
        Buscado = txtBuscado.getText();
        if(chkFiltro.isSelected()){
            //el valor 0 sera usado en la db para saber si se selecciono una marca o categoria
            int indexMarca = cmbMarca.getSelectedIndex();
            int indexSubcategoria = cmbSubCategoria.getSelectedIndex();
            if(chkEnstock.isSelected()){
                jTable1.setModel(MetodoProducto.BuscarProductoconFiltroEnStock(Buscado, indexMarca,indexSubcategoria));
            }else{
                jTable1.setModel(MetodoProducto.BuscarProductoconFiltro(Buscado, indexMarca,indexSubcategoria));
            }
        }else{
            if(chkEnstock.isSelected()){
                jTable1.setModel(MetodoProducto.BuscarProductoEnStock(Buscado));
            }else{
                jTable1.setModel(MetodoProducto.BuscarProducto(Buscado));
            }
        }
        //jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        //jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
        //jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(500);
        //jTable1.getColumnModel().getColumn(5).setPreferredWidth(30);
        //jTable1.getColumnModel().getColumn(6).setPreferredWidth(20);
    }
    public String getBuscado(){
        return Buscado;
    }
    public void setBuscado(String buscado){
        this.Buscado = buscado;
    }
    public String getTxtBuscado(){
        return txtBuscado.getText();
    }
    public void setTxtBuscado(String buscado){
        txtBuscado.setText(buscado);
    }
    public int getIndexInsertar(){
        return indexInsertar;
    }
    public void setIndexInsertar(int index){
        this.indexInsertar = index;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscado = new jtextfieldround.JTextFieldRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_buscarCategoria = new javax.swing.JButton();
        cmbMarca = new javax.swing.JComboBox<>();
        cmbSubCategoria = new javax.swing.JComboBox<>();
        chkFiltro = new javax.swing.JCheckBox();
        chkEnstock = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(220, 220, 220));
        setClosable(true);

        txtBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_buscarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_lupa_desactivada.png"))); // NOI18N
        btn_buscarCategoria.setBorder(null);
        btn_buscarCategoria.setBorderPainted(false);
        btn_buscarCategoria.setContentAreaFilled(false);
        btn_buscarCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_lupa_activo.png"))); // NOI18N
        btn_buscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCategoriaActionPerformed(evt);
            }
        });

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSubCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chkFiltro.setBackground(new java.awt.Color(220, 220, 220));
        chkFiltro.setForeground(new java.awt.Color(0, 0, 0));
        chkFiltro.setText("Filtro");

        chkEnstock.setBackground(new java.awt.Color(220, 220, 220));
        chkEnstock.setForeground(new java.awt.Color(0, 0, 0));
        chkEnstock.setText("En Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscarCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(chkEnstock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarCategoria)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkFiltro)
                        .addComponent(chkEnstock)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER ){
            BuscarCargarTabla();
        }
    }//GEN-LAST:event_txtBuscadoKeyPressed

    private void btn_buscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCategoriaActionPerformed
        // TODO add your handling code here:
        BuscarCargarTabla();
    }//GEN-LAST:event_btn_buscarCategoriaActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && getFrmAIndexar() == 1){
            frmVentas.InsertarProducto(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()), indexInsertar);
            dispose();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER && getFrmAIndexar() == 2){
            frmIngreso.InsertarProducto(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()), indexInsertar);
            dispose();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER && getFrmAIndexar() == 3){
            int row = jTable1.getSelectedRow();
            String prod = jTable1.getValueAt(row, 3).toString() + " " +jTable1.getValueAt(row, 4).toString();
            LugarDeProducto.InsertarProducto(Integer.parseInt(jTable1.getValueAt(row, 0).toString()), prod);
            dispose();
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER && getFrmAIndexar() == 4){
            int row = jTable1.getSelectedRow();
            int prod = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            RegistroProductos.setId_producto(prod);
            RegistroProductos.insertarDatos();
            dispose();
        }
    }//GEN-LAST:event_jTable1KeyPressed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarCategoria;
    private javax.swing.JCheckBox chkEnstock;
    private javax.swing.JCheckBox chkFiltro;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbSubCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private jtextfieldround.JTextFieldRound txtBuscado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the frmAIndexar
     */
    public int getFrmAIndexar() {
        return frmAIndexar;
    }

    /**
     * @param frmAIndexar the frmAIndexar to set
     */
    public void setFrmAIndexar(int frmAIndexar) {
        this.frmAIndexar = frmAIndexar;
    }
}
