/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;

import Utilitaries.Funcionalidades;
import Utilitaries.MetodoClientesProveedor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author Paul
 */
public class frmAsociacionPseudonimos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAsociacionPseudonimos
     */
    private int id_cliente_proveedor;
    private int id_seudonimo;
    public frmAsociacionPseudonimos() {
        initComponents();
        BUSCAR_CLIENTE_PROVEEDOR();
        BUSCAR_SEUDONIMO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeudonimo = new javax.swing.JTable();
        txtBusca_Seudonimo = new jtextfieldround.JTextFieldRound();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClienteProveedor = new javax.swing.JTable();
        txtBusca_ClienteProveedor = new jtextfieldround.JTextFieldRound();
        chkDocumento = new javax.swing.JCheckBox();
        chkNombre = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        txtCliente_proveedor_seleccionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSeudonimo_seleccionado = new javax.swing.JTextField();
        btnAsociar = new javax.swing.JButton();
        btnNuevo_Seudonimo = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 220, 220));
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "SEUDONIMO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        tblSeudonimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSeudonimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSeudonimoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeudonimo);

        txtBusca_Seudonimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusca_SeudonimoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(txtBusca_Seudonimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtBusca_Seudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "CLIENTE / PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        tblClienteProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClienteProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClienteProveedorKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblClienteProveedor);

        txtBusca_ClienteProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusca_ClienteProveedorKeyPressed(evt);
            }
        });

        chkDocumento.setBackground(new java.awt.Color(220, 220, 220));
        chkDocumento.setForeground(new java.awt.Color(0, 0, 0));
        chkDocumento.setSelected(true);
        chkDocumento.setText("Por Documento");
        chkDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDocumentoActionPerformed(evt);
            }
        });

        chkNombre.setBackground(new java.awt.Color(220, 220, 220));
        chkNombre.setForeground(new java.awt.Color(0, 0, 0));
        chkNombre.setText("Por Nombre");
        chkNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBusca_ClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkNombre)))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusca_ClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkNombre)
                        .addComponent(chkDocumento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ASOCIACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        txtCliente_proveedor_seleccionado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCliente_proveedor_seleccionado.setText("NINGUNO SELECCIONADO");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("< >");

        txtSeudonimo_seleccionado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSeudonimo_seleccionado.setText("NINGUNO SELECCIONADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCliente_proveedor_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSeudonimo_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente_proveedor_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtSeudonimo_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAsociar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAsociar.setText("ASOCIAR");
        btnAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarActionPerformed(evt);
            }
        });

        btnNuevo_Seudonimo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNuevo_Seudonimo.setText("NUEVO SEUDONIMO");
        btnNuevo_Seudonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo_SeudonimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevo_Seudonimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNuevo_Seudonimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static void hidecolumn(JTable tabla, int column_index){
        TableColumn column = tabla.getColumnModel().getColumn(column_index);
        column.setMinWidth(0);
        column.setMaxWidth(0);
        column.setWidth(0);
        column.setPreferredWidth(0);
    }
    public void BUSCAR_CLIENTE_PROVEEDOR(){
        String buscado = txtBusca_ClienteProveedor.getText();
        if(chkDocumento.isSelected()){
            tblClienteProveedor.setModel(MetodoClientesProveedor.BuscarPorDocumento(buscado));
        }
        if(chkNombre.isSelected()){
            tblClienteProveedor.setModel(MetodoClientesProveedor.BuscarPorNombre(buscado));
        }
        hidecolumn(tblClienteProveedor, 0);
        hidecolumn(tblClienteProveedor, 1);
        hidecolumn(tblClienteProveedor, 4);
        hidecolumn(tblClienteProveedor, 5);
        hidecolumn(tblClienteProveedor, 6);
        tblClienteProveedor.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
    public void BUSCAR_SEUDONIMO(){
        String buscado = txtBusca_Seudonimo.getText();
        tblSeudonimo.setModel(MetodoClientesProveedor.Buscar_Seudonimo(buscado));
        hidecolumn(tblSeudonimo, 0);
        hidecolumn(tblSeudonimo, 2);
    }
    public void MarcarFiltros(int i){
        
        if(i == 1){
            chkDocumento.setSelected(true);
            chkNombre.setSelected(false);
        }else if(i == 2){
            chkDocumento.setSelected(false);
            chkNombre.setSelected(true);
        }
        txtBusca_ClienteProveedor.setText(null);
        txtBusca_ClienteProveedor.requestFocus();
        BUSCAR_CLIENTE_PROVEEDOR();
    }
    private void chkDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDocumentoActionPerformed
        // TODO add your handling code here:
        MarcarFiltros(1);
    }//GEN-LAST:event_chkDocumentoActionPerformed

    private void chkNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNombreActionPerformed
        // TODO add your handling code here:
        MarcarFiltros(2);
    }//GEN-LAST:event_chkNombreActionPerformed

    private void tblClienteProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClienteProveedorKeyPressed
        // TODO add your handling code here:
        int row = tblClienteProveedor.getSelectedRow();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && row != -1){
            txtCliente_proveedor_seleccionado.setText(tblClienteProveedor.getValueAt(row, 3).toString());
            setId_cliente_proveedor(Integer.parseInt(tblClienteProveedor.getValueAt(row, 0).toString()));
        }
    }//GEN-LAST:event_tblClienteProveedorKeyPressed

    private void txtBusca_ClienteProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusca_ClienteProveedorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            BUSCAR_CLIENTE_PROVEEDOR();
        }
    }//GEN-LAST:event_txtBusca_ClienteProveedorKeyPressed

    private void txtBusca_SeudonimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusca_SeudonimoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            BUSCAR_SEUDONIMO();
        }
    }//GEN-LAST:event_txtBusca_SeudonimoKeyPressed

    private void tblSeudonimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSeudonimoKeyPressed
        // TODO add your handling code here:
        int row = tblSeudonimo.getSelectedRow();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && row != -1){
            txtSeudonimo_seleccionado.setText(tblSeudonimo.getValueAt(row, 1).toString());
            setId_seudonimo(Integer.parseInt(tblSeudonimo.getValueAt(row, 0).toString()));
        }
    }//GEN-LAST:event_tblSeudonimoKeyPressed

    private void btnAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarActionPerformed
        // TODO add your handling code here:
        if(id_cliente_proveedor == 0 || id_seudonimo == 0){
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR LOS DOS CAMPOS PARA ASOCIAR");    
        }else{
            int valor = JOptionPane.showConfirmDialog(
                    null,
                    "ESTA SEGURO DE REALIZAR ESTA ASOCIACION",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION
                );
            if(valor == JOptionPane.YES_OPTION){

                MetodoClientesProveedor.Asociar_ClienteProveedor_Seudonimo(id_cliente_proveedor, id_seudonimo);
            }
        }
    }//GEN-LAST:event_btnAsociarActionPerformed

    private void btnNuevo_SeudonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo_SeudonimoActionPerformed
        // TODO add your handling code here:
        RegistrarSeudonimos nuevo = new RegistrarSeudonimos();
        Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
    }//GEN-LAST:event_btnNuevo_SeudonimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociar;
    private javax.swing.JButton btnNuevo_Seudonimo;
    public javax.swing.JCheckBox chkDocumento;
    public javax.swing.JCheckBox chkNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblClienteProveedor;
    private javax.swing.JTable tblSeudonimo;
    private jtextfieldround.JTextFieldRound txtBusca_ClienteProveedor;
    private jtextfieldround.JTextFieldRound txtBusca_Seudonimo;
    private javax.swing.JTextField txtCliente_proveedor_seleccionado;
    private javax.swing.JTextField txtSeudonimo_seleccionado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the id_cliente_proveedor
     */
    public int getId_cliente_proveedor() {
        return id_cliente_proveedor;
    }

    /**
     * @param id_cliente_proveedor the id_cliente_proveedor to set
     */
    public void setId_cliente_proveedor(int id_cliente_proveedor) {
        this.id_cliente_proveedor = id_cliente_proveedor;
    }

    /**
     * @return the id_seudonimo
     */
    public int getId_seudonimo() {
        return id_seudonimo;
    }

    /**
     * @param id_seudonimo the id_seudonimo to set
     */
    public void setId_seudonimo(int id_seudonimo) {
        this.id_seudonimo = id_seudonimo;
    }
}
