/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;

import static Frames.frmVentas.Render;
import static Frames.frmVentas.getLista;
import static Frames.frmVentas.jTable1;
import static Frames.frmVentas.setLista;
import Utilitaries.Compra;
//import static Frames.frmVentas.setTipoDocumento;
import Utilitaries.Funcionalidades;
import Utilitaries.MetodoTipos;
import Utilitaries.Producto;
import Utilitaries.Venta;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul
 */
public class frmIngreso extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCompras
     */
    private static int id_compra;
    private static int TipoDocumento;
    private static ArrayList<Producto> lista;
    private static int ID_ClienteProveedor;
    private static int ID_Vendedor;
    private static String DireccionCliente;
    private static String EmailCliente;
    public frmIngreso(Compra cmp){
        initComponents();
        Cargar();
        CambiarPrefijo();
        id_compra = cmp.getId_compra();
        cmbTipoCondicion.setSelectedIndex(cmp.getId_tipo_condicion()-1);
        cmbTipoComprobante.setSelectedIndex(cmp.getId_tipo_comprobante()-1);
        cmbAlmacen.setSelectedIndex(cmp.getId_almacen()-1);
        cmbTipoPago.setSelectedIndex(cmp.getId_tipo_pago()-1);
        setID_ClienteProveedor(cmp.getId_clienteproveedor());
        txtCorrelativo.setText(cmp.getCorrelativo() + "");
        setLista(cmp.getLista());
        Render();
    }
    public frmIngreso() {
        initComponents();
        Cargar();
    }
    
    public static void Render(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setRowCount(getLista().size()+1);
        double PrecioTotal = 0;
        double impuesTotal = 0;
        double PrecioBrutoTotal = 0;
        int cont = 0;
        for(Producto item : getLista()){
            model.setValueAt(item.getDescripcion(), cont, 0);
            model.setValueAt(item.getCantidadVenta(), cont, 1);
            model.setValueAt(item.getPrecio(), cont, 2);
            model.setValueAt(item.getPrecioBruto(), cont, 3);
            model.setValueAt(item.getImpuesto(), cont, 4);
            model.setValueAt(item.getPrecioNeto(), cont, 5);
            model.setValueAt(item.getPrecioNeto(), cont, 6);
            PrecioBrutoTotal += item.getPrecioBruto();
            PrecioTotal += item.getPrecioNeto();
            impuesTotal += item.getImpuesto();
            cont++;
        }
        jTable1.setModel(model);
        txtGravada.setText(PrecioBrutoTotal + "");
        txtImpuestoTotal.setText(impuesTotal + "");
        txtImporteTotal.setText(PrecioTotal + "");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoComprobante = new javax.swing.JComboBox<>();
        txtPrefijo = new javax.swing.JTextField();
        txtCorrelativo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarClienteProveedor = new javax.swing.JTextField();
        txtNombreClienteProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdentidadClienteProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbAlmacen = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoCondicion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbTipoPago = new javax.swing.JComboBox<>();
        lblVendedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtImporteTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtImpuestoTotal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtGravada = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 220, 220));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(857, 685));

        jPanel2.setBackground(new java.awt.Color(33, 97, 140));
        jPanel2.setForeground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(943, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GENERADOR COMPRAS/INGRESO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 316, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 315, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Documento:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(33, 97, 140))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar RUC o DNI:");

        cmbTipoComprobante.setBackground(new java.awt.Color(240, 240, 240));
        cmbTipoComprobante.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cmbTipoComprobante.setForeground(new java.awt.Color(0, 0, 0));
        cmbTipoComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACTURA", "BOLETA" }));
        cmbTipoComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoComprobanteActionPerformed(evt);
            }
        });

        txtPrefijo.setBackground(new java.awt.Color(240, 240, 240));
        txtPrefijo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtPrefijo.setForeground(new java.awt.Color(0, 0, 0));
        txtPrefijo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrefijo.setText("F001");
        txtPrefijo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtCorrelativo.setBackground(new java.awt.Color(240, 240, 240));
        txtCorrelativo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCorrelativo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorrelativo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorrelativo.setText("00000");

        jLabel2.setBackground(new java.awt.Color(220, 220, 220));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("-");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DOCUMENTO:");

        txtBuscarClienteProveedor.setBackground(new java.awt.Color(240, 240, 240));
        txtBuscarClienteProveedor.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarClienteProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBuscarClienteProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarClienteProveedorKeyPressed(evt);
            }
        });

        txtNombreClienteProveedor.setEditable(false);
        txtNombreClienteProveedor.setBackground(new java.awt.Color(240, 240, 240));
        txtNombreClienteProveedor.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreClienteProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CLIENTE:");

        txtIdentidadClienteProveedor.setEditable(false);
        txtIdentidadClienteProveedor.setBackground(new java.awt.Color(240, 240, 240));
        txtIdentidadClienteProveedor.setForeground(new java.awt.Color(0, 0, 0));
        txtIdentidadClienteProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Doc.Ident:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentidadClienteProveedor)
                    .addComponent(txtNombreClienteProveedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBuscarClienteProveedor))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentidadClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Internos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(33, 97, 140))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("VENDEDOR:");

        cmbAlmacen.setBackground(new java.awt.Color(240, 240, 240));
        cmbAlmacen.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cmbAlmacen.setForeground(new java.awt.Color(0, 0, 0));
        cmbAlmacen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACTURA", "BOLETA" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ALMACEN:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CONDICION:");

        cmbTipoCondicion.setBackground(new java.awt.Color(240, 240, 240));
        cmbTipoCondicion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cmbTipoCondicion.setForeground(new java.awt.Color(0, 0, 0));
        cmbTipoCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACTURA", "BOLETA" }));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("TIPO DE PAGO:");

        cmbTipoPago.setBackground(new java.awt.Color(240, 240, 240));
        cmbTipoPago.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cmbTipoPago.setForeground(new java.awt.Color(0, 0, 0));
        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACTURA", "BOLETA" }));

        lblVendedor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblVendedor.setForeground(new java.awt.Color(0, 0, 0));
        lblVendedor.setText("NULL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVendedor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipoCondicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblVendedor)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(225, 225, 225));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Cant", "Precio und", "Precio bruto", "Impuesto", "Precio Neto", "Total"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setAutoscrolls(false);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(420);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Busqueda x Codigo de Barras (S/N):");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(240, 240, 240));
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(220, 220, 220));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/VBus.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(33, 97, 140));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("IMPORTE TOTAL");

        txtImporteTotal.setEditable(false);
        txtImporteTotal.setBackground(new java.awt.Color(240, 240, 240));
        txtImporteTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtImporteTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(33, 97, 140));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("I.G.V. (18.00%)");

        txtImpuestoTotal.setEditable(false);
        txtImpuestoTotal.setBackground(new java.awt.Color(240, 240, 240));
        txtImpuestoTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtImpuestoTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtImpuestoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImpuestoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(33, 97, 140));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("GRAVADA");

        txtGravada.setEditable(false);
        txtGravada.setBackground(new java.awt.Color(240, 240, 240));
        txtGravada.setForeground(new java.awt.Color(0, 0, 0));
        txtGravada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtGravada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGravada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(210, 210, 210));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/comp1.png"))); // NOI18N
        jButton2.setText("[CTRL+DEL] Borra Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(210, 210, 210));
        btnGenerar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtNota.setBackground(new java.awt.Color(210, 210, 210));
        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane2.setViewportView(txtNota);

        jLabel15.setBackground(new java.awt.Color(220, 220, 220));
        jLabel15.setForeground(new java.awt.Color(33, 97, 140));
        jLabel15.setText("Notas / Observaciones:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGenerar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(259, 259, 259))
                            .addComponent(jScrollPane2)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerar)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static void AgregarFilaVacia(DefaultTableModel model){
        
        Object[] emptyRow = new Object[model.getColumnCount()];
        model.addRow(emptyRow);
    }
    public static void InsertarProducto(int ID, int index){
        if(getLista().size() > index){
            getLista().set(index, new Producto(ID));
        }else{
            getLista().add(new Producto(ID)); 
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            AgregarFilaVacia(model);
        }
        Render();
    }
    private void txtBuscarClienteProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteProveedorKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            BuscarClienteProveedor nuevo = new BuscarClienteProveedor();
            nuevo.settxtBuscar(txtBuscarClienteProveedor.getText());
            nuevo.setFrmAIndexar(2);
            Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
            //InsertarConSN(txtBuscarSerie.getText());
        }
        
    }//GEN-LAST:event_txtBuscarClienteProveedorKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        getLista().remove(jTable1.getSelectedRow());
        Render();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        int cantidad = 0;
        double nuevoPrecio = 0;
        if(column != 0 && jTable1.getValueAt(row, column) != null){
            cantidad = Integer.parseInt(jTable1.getValueAt(row, 1).toString());
            nuevoPrecio = Double.parseDouble(jTable1.getValueAt(row, 2).toString());
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && column == 0 && jTable1.getValueAt(row, column) != null){
            BuscarProducto nuevo = new BuscarProducto();
            String buscado = jTable1.getValueAt(row, column).toString();
            nuevo.setBuscado(buscado);
            nuevo.setTxtBuscado(buscado);
            nuevo.setIndexInsertar(row);//se envia la fila ah modificar
            nuevo.setFrmAIndexar(2);
            Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER && column == 1 && jTable1.getValueAt(row, 1) != null){
            
            //RecarculoPrecios(Integer.parseInt(jTable1.getValueAt(row, 1).toString()),Double.parseDouble(jTable1.getValueAt(row, 2).toString()), row);
            //RecarculoPrecios((int) ,(double) , row);
            getLista().get(row).setCantidadVenta(cantidad);
            getLista().get(row).setPrecio(nuevoPrecio);
            Render();
            
            ListarSN nuevo = new ListarSN();
            nuevo.setIndex(row);
            nuevo.setAfectado(1);
            Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
            
        }else if(evt.getKeyCode() == KeyEvent.VK_ENTER && column == 2 && jTable1.getValueAt(row, 2) != null){
            //RecarculoPrecios(Integer.parseInt(jTable1.getValueAt(row, 1).toString()),Double.parseDouble(jTable1.getValueAt(row, 2).toString()), row);
            getLista().get(row).setCantidadVenta(cantidad);
            getLista().get(row).setPrecio(nuevoPrecio);
            Render();
        }
        
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void cmbTipoComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoComprobanteActionPerformed
        // TODO add your handling code here:
        CambiarPrefijo();
    }//GEN-LAST:event_cmbTipoComprobanteActionPerformed
    private void RegistrarDATABASE(){
        Compra registro = new Compra();
        registro.setId_compra(id_compra);
        registro.setId_tipo_comprobante(cmbTipoComprobante.getSelectedIndex() + 1);
        registro.setCorrelativo(Integer.parseInt(txtCorrelativo.getText()));
        registro.setId_clienteproveedor(ID_ClienteProveedor);
        registro.setId_usuario(ID_USUARIO);
        registro.setId_tipo_condicion(cmbTipoCondicion.getSelectedIndex() + 1);
        registro.setId_almacen(cmbAlmacen.getSelectedIndex() + 1);
        registro.setFecha(LocalDate.now());
        registro.setId_tipo_pago(cmbTipoPago.getSelectedIndex() + 1);
        registro.setGravada(Double.parseDouble(txtGravada.getText()));
        registro.setImpuesto(Double.parseDouble(txtImpuestoTotal.getText()));
        registro.setTotal(Double.parseDouble(txtImporteTotal.getText()));
        registro.setNota(txtNota.getText());
        registro.setLista(getLista());
        registro.Registrar();
    }
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        RegistrarDATABASE();
        dispose();
    }//GEN-LAST:event_btnGenerarActionPerformed
    private int ID_USUARIO;
    private int ID_CARGO;
    private String[] PrefijosComprobante;
    private void Cargar(){
        String[] Almacenes = MetodoTipos.BuscarAlmacenes("");
        String[] TipoCondicion = MetodoTipos.BuscarCondicion("");
        String[] TipoPago = MetodoTipos.NombrePagos();
        String[] NombreComprobantes = MetodoTipos.NombresComprobantes();
        PrefijosComprobante = MetodoTipos.PrefijosComprobantes();
        cmbTipoComprobante.removeAllItems();
        cmbAlmacen.removeAllItems();    
        cmbTipoCondicion.removeAllItems();
        cmbTipoPago.removeAllItems();
        
        for(String item : NombreComprobantes){
           cmbTipoComprobante.addItem(item);
        }
        for(String item : Almacenes){
           cmbAlmacen.addItem(item);
        }
        for(String item : TipoCondicion){
           cmbTipoCondicion.addItem(item);
        }
        for(String item : TipoPago){
           cmbTipoPago.addItem(item);
        }
        setLista(new ArrayList<Producto>());
    }
    private void CambiarPrefijo(){
        int index = cmbTipoComprobante.getSelectedIndex();
        if(index == -1) index = 0;
        txtPrefijo.setText(PrefijosComprobante[index]);
        switch(index){
            case 0: setTipoDocumento(1); break;
            case 1: setTipoDocumento(6); break;
        }
    }
    public static void InsertarSeries(int index, ArrayList<String> Series){
        lista.get(index).setCantidadVenta(Series.size());
        lista.get(index).setSeries(Series);
        Render();
    }
    public int getID_USUARIO(){
        return ID_USUARIO;
    }
    public void setID_USUARIO(int number){
        this.ID_USUARIO = number;
    }
    public int getID_CARGO(){
        return ID_CARGO;
    }
    public void setID_CARGO(int number){
        this.ID_CARGO = number;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbAlmacen;
    private javax.swing.JComboBox<String> cmbTipoComprobante;
    private javax.swing.JComboBox<String> cmbTipoCondicion;
    private javax.swing.JComboBox<String> cmbTipoPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private static javax.swing.JLabel lblVendedor;
    private javax.swing.JTextField txtBuscarClienteProveedor;
    private javax.swing.JTextField txtCorrelativo;
    private static javax.swing.JTextField txtGravada;
    private static javax.swing.JTextField txtIdentidadClienteProveedor;
    private static javax.swing.JTextField txtImporteTotal;
    private static javax.swing.JTextField txtImpuestoTotal;
    private static javax.swing.JTextField txtNombreClienteProveedor;
    private static javax.swing.JTextArea txtNota;
    private javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the TipoDocumento
     */
    public static int getTipoDocumento() {
        return TipoDocumento;
    }

    /**
     * @param aTipoDocumento the TipoDocumento to set
     */
    public static void setTipoDocumento(int aTipoDocumento) {
        TipoDocumento = aTipoDocumento;
    }

    /**
     * @return the lista
     */
    public static ArrayList<Producto> getLista() {
        return lista;
    }

    /**
     * @param aLista the lista to set
     */
    public static void setLista(ArrayList<Producto> aLista) {
        lista = aLista;
    }

    /**
     * @return the ID_ClienteProveedor
     */
    public static int getID_ClienteProveedor() {
        return ID_ClienteProveedor;
    }

    /**
     * @param aID_ClienteProveedor the ID_ClienteProveedor to set
     */
    public static void setID_ClienteProveedor(int aID_ClienteProveedor) {
        ID_ClienteProveedor = aID_ClienteProveedor;
    }
    public static void settxtIdentidadClienteProveedor(String Identidad){
        txtIdentidadClienteProveedor.setText(Identidad);
        
    }
    public static void settxtNombreClienteProveedor(String Nombre){
        txtNombreClienteProveedor.setText(Nombre);
    }

    /**
     * @return the DireccionCliente
     */
    public static String getDireccionCliente() {
        return DireccionCliente;
    }

    /**
     * @param aDireccionCliente the DireccionCliente to set
     */
    public static void setDireccionCliente(String aDireccionCliente) {
        DireccionCliente = aDireccionCliente;
    }

    /**
     * @return the EmailCliente
     */
    public static String getEmailCliente() {
        return EmailCliente;
    }

    /**
     * @param aEmailCliente the EmailCliente to set
     */
    public static void setEmailCliente(String aEmailCliente) {
        EmailCliente = aEmailCliente;
    }

    /**
     * @return the ID_Vendedor
     */
    public static int getID_Vendedor() {
        return ID_Vendedor;
    }

    /**
     * @param aID_Vendedor the ID_Vendedor to set
     */
    public static void setID_Vendedor(int aID_Vendedor) {
        ID_Vendedor = aID_Vendedor;
    }
}
