/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import javax.swing.JInternalFrame;
import javax.swing.JRootPane;
/*
import Frames.RegistroProductos;
import Frames.RegistroClientes;
import Frames.RegistroCategoria;
import Frames.RegistroMarca;
*/
/**
 *
 * @author Paul
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        tbn_escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_Archivo = new javax.swing.JMenu();
        mni_CerrarSesion = new javax.swing.JMenuItem();
        mni_Salir = new javax.swing.JMenuItem();
        mnu_Registro = new javax.swing.JMenu();
        mni_Reg_Productos = new javax.swing.JMenuItem();
        mni_Reg_Clientes = new javax.swing.JMenuItem();
        mni_Reg_Empleados = new javax.swing.JMenuItem();
        mni_Reg_Categorias = new javax.swing.JMenuItem();
        mni_Reg_marcas = new javax.swing.JMenuItem();
        mni_Reg_Correlativos = new javax.swing.JMenuItem();
        mni_Reg_Asociacion_Seudonimos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnu_Movimientos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mni_Mov_Compras = new javax.swing.JMenuItem();
        mnu_Mov_Salidas = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mni_Mov_Transferencia = new javax.swing.JMenuItem();
        mni_Mov_RASTREARPRODUCTO = new javax.swing.JMenuItem();
        mnu_Consultas = new javax.swing.JMenu();
        mni_Cons_Compras = new javax.swing.JMenuItem();
        mni_Cons_Usuarios = new javax.swing.JMenuItem();
        mni_Cons_Ventas = new javax.swing.JMenuItem();
        mni_Cons_Productos = new javax.swing.JMenuItem();
        mnu_Reportes = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        mnu_Administrador = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 97, 140));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbn_escritorio.setBackground(new java.awt.Color(33, 97, 140));
        tbn_escritorio.setForeground(new java.awt.Color(33, 97, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo1072cuadradoblanco.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(33, 97, 140));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("USUARIO:");

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("NULL");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CARGO:");

        lblCargo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 0, 0));
        lblCargo.setText("NULL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCargo)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbn_escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbn_escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tbn_escritorioLayout = new javax.swing.GroupLayout(tbn_escritorio);
        tbn_escritorio.setLayout(tbn_escritorioLayout);
        tbn_escritorioLayout.setHorizontalGroup(
            tbn_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbn_escritorioLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tbn_escritorioLayout.setVerticalGroup(
            tbn_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbn_escritorioLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        mnu_Archivo.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Archivo.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ar1.png"))); // NOI18N
        mnu_Archivo.setText("Archivo");
        mnu_Archivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        mni_CerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        mni_CerrarSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_CerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        mni_CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sa1.png"))); // NOI18N
        mni_CerrarSesion.setText("Cerrar Sesion");
        mnu_Archivo.add(mni_CerrarSesion);

        mni_Salir.setBackground(new java.awt.Color(204, 204, 204));
        mni_Salir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Salir.setForeground(new java.awt.Color(0, 0, 0));
        mni_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ce2.png"))); // NOI18N
        mni_Salir.setText("Salir");
        mnu_Archivo.add(mni_Salir);

        jMenuBar1.add(mnu_Archivo);

        mnu_Registro.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Registro.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reg.png"))); // NOI18N
        mnu_Registro.setText("Registro");
        mnu_Registro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        mni_Reg_Productos.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_Productos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_Productos.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/prod2.png"))); // NOI18N
        mni_Reg_Productos.setText("Productos");
        mni_Reg_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Reg_ProductosActionPerformed(evt);
            }
        });
        mnu_Registro.add(mni_Reg_Productos);

        mni_Reg_Clientes.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_Clientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_Clientes.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cli1.png"))); // NOI18N
        mni_Reg_Clientes.setText("Clientes y Proveedores");
        mni_Reg_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Reg_ClientesActionPerformed(evt);
            }
        });
        mnu_Registro.add(mni_Reg_Clientes);

        mni_Reg_Empleados.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_Empleados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_Empleados.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_Empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/emp1.png"))); // NOI18N
        mni_Reg_Empleados.setText("Empleados");
        mnu_Registro.add(mni_Reg_Empleados);

        mni_Reg_Categorias.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_Categorias.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_Categorias.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_Categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icon_categoria-22.png"))); // NOI18N
        mni_Reg_Categorias.setText("Categorias");
        mni_Reg_Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Reg_CategoriasActionPerformed(evt);
            }
        });
        mnu_Registro.add(mni_Reg_Categorias);

        mni_Reg_marcas.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_marcas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_marcas.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_marcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icon_categoria-22.png"))); // NOI18N
        mni_Reg_marcas.setText("Marcas");
        mni_Reg_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Reg_marcasActionPerformed(evt);
            }
        });
        mnu_Registro.add(mni_Reg_marcas);

        mni_Reg_Correlativos.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_Correlativos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_Correlativos.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_Correlativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icon_categoria-22.png"))); // NOI18N
        mni_Reg_Correlativos.setText("Correlativos");
        mni_Reg_Correlativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Reg_CorrelativosActionPerformed(evt);
            }
        });
        mnu_Registro.add(mni_Reg_Correlativos);

        mni_Reg_Asociacion_Seudonimos.setBackground(new java.awt.Color(204, 204, 204));
        mni_Reg_Asociacion_Seudonimos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Reg_Asociacion_Seudonimos.setForeground(new java.awt.Color(0, 0, 0));
        mni_Reg_Asociacion_Seudonimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icon_categoria-22.png"))); // NOI18N
        mni_Reg_Asociacion_Seudonimos.setText("Asociacion Seudonimos");
        mni_Reg_Asociacion_Seudonimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Reg_Asociacion_SeudonimosActionPerformed(evt);
            }
        });
        mnu_Registro.add(mni_Reg_Asociacion_Seudonimos);

        jMenu1.setText("Tipos");

        jMenuItem1.setText("Tipo Condicion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Tipo Comprobante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Tipo Pago");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        mnu_Registro.add(jMenu1);

        jMenuBar1.add(mnu_Registro);

        mnu_Movimientos.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Movimientos.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Movimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mov.png"))); // NOI18N
        mnu_Movimientos.setText("Acciones");
        mnu_Movimientos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mnu_Movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_MovimientosActionPerformed(evt);
            }
        });

        jMenu2.setBackground(new java.awt.Color(204, 204, 204));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/co1.png"))); // NOI18N
        jMenu2.setText("INGRESOS");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        mni_Mov_Compras.setBackground(new java.awt.Color(204, 204, 204));
        mni_Mov_Compras.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        mni_Mov_Compras.setForeground(new java.awt.Color(0, 0, 0));
        mni_Mov_Compras.setText("Compras");
        mni_Mov_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Mov_ComprasActionPerformed(evt);
            }
        });
        jMenu2.add(mni_Mov_Compras);

        mnu_Movimientos.add(jMenu2);

        mnu_Mov_Salidas.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Mov_Salidas.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Mov_Salidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/vent1.png"))); // NOI18N
        mnu_Mov_Salidas.setText("SALIDAS");
        mnu_Mov_Salidas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem4.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem4.setText("VENTAS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnu_Mov_Salidas.add(jMenuItem4);

        mnu_Movimientos.add(mnu_Mov_Salidas);

        mni_Mov_Transferencia.setBackground(new java.awt.Color(204, 204, 204));
        mni_Mov_Transferencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Mov_Transferencia.setForeground(new java.awt.Color(0, 0, 0));
        mni_Mov_Transferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trans_product.png"))); // NOI18N
        mni_Mov_Transferencia.setText("TRANSFERENCIAS");
        mni_Mov_Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Mov_TransferenciaActionPerformed(evt);
            }
        });
        mnu_Movimientos.add(mni_Mov_Transferencia);

        mni_Mov_RASTREARPRODUCTO.setBackground(new java.awt.Color(204, 204, 204));
        mni_Mov_RASTREARPRODUCTO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Mov_RASTREARPRODUCTO.setForeground(new java.awt.Color(0, 0, 0));
        mni_Mov_RASTREARPRODUCTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trans_product.png"))); // NOI18N
        mni_Mov_RASTREARPRODUCTO.setText("RASTREAR PRODC");
        mni_Mov_RASTREARPRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Mov_RASTREARPRODUCTOActionPerformed(evt);
            }
        });
        mnu_Movimientos.add(mni_Mov_RASTREARPRODUCTO);

        jMenuBar1.add(mnu_Movimientos);

        mnu_Consultas.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Consultas.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cons.png"))); // NOI18N
        mnu_Consultas.setText("Consultas");
        mnu_Consultas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        mni_Cons_Compras.setBackground(new java.awt.Color(204, 204, 204));
        mni_Cons_Compras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Cons_Compras.setForeground(new java.awt.Color(0, 0, 0));
        mni_Cons_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cons1.png"))); // NOI18N
        mni_Cons_Compras.setText("Compras");
        mni_Cons_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Cons_ComprasActionPerformed(evt);
            }
        });
        mnu_Consultas.add(mni_Cons_Compras);

        mni_Cons_Usuarios.setBackground(new java.awt.Color(204, 204, 204));
        mni_Cons_Usuarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Cons_Usuarios.setForeground(new java.awt.Color(0, 0, 0));
        mni_Cons_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cons3.png"))); // NOI18N
        mni_Cons_Usuarios.setText("Usuarios");
        mni_Cons_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Cons_UsuariosActionPerformed(evt);
            }
        });
        mnu_Consultas.add(mni_Cons_Usuarios);

        mni_Cons_Ventas.setBackground(new java.awt.Color(204, 204, 204));
        mni_Cons_Ventas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Cons_Ventas.setForeground(new java.awt.Color(0, 0, 0));
        mni_Cons_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cons6.png"))); // NOI18N
        mni_Cons_Ventas.setText("Ventas");
        mni_Cons_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Cons_VentasActionPerformed(evt);
            }
        });
        mnu_Consultas.add(mni_Cons_Ventas);

        mni_Cons_Productos.setBackground(new java.awt.Color(204, 204, 204));
        mni_Cons_Productos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mni_Cons_Productos.setForeground(new java.awt.Color(0, 0, 0));
        mni_Cons_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cons4.png"))); // NOI18N
        mni_Cons_Productos.setText("Lista Productos");
        mni_Cons_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_Cons_ProductosActionPerformed(evt);
            }
        });
        mnu_Consultas.add(mni_Cons_Productos);

        jMenuBar1.add(mnu_Consultas);

        mnu_Reportes.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Reportes.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rep.png"))); // NOI18N
        mnu_Reportes.setText("Reportes");
        mnu_Reportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem17.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem17.setText("Cobranza");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        mnu_Reportes.add(jMenuItem17);

        jMenuItem18.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem18.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem18.setText("en desarrollo");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        mnu_Reportes.add(jMenuItem18);

        jMenuItem19.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem19.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem19.setText("en desarrollo");
        mnu_Reportes.add(jMenuItem19);

        jMenuBar1.add(mnu_Reportes);

        mnu_Administrador.setBackground(new java.awt.Color(204, 204, 204));
        mnu_Administrador.setForeground(new java.awt.Color(0, 0, 0));
        mnu_Administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/adm.png"))); // NOI18N
        mnu_Administrador.setText("Administrador");
        mnu_Administrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem20.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem20.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/us1.png"))); // NOI18N
        jMenuItem20.setText("Usuarios");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        mnu_Administrador.add(jMenuItem20);

        jMenuBar1.add(mnu_Administrador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbn_escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbn_escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int ID_USUARIO;
    private int ID_CARGO;
    public int getID_USUARIO(){
        return ID_USUARIO;
    }
    public void setID_USUARIO(int number){
        this.ID_USUARIO = number;
    }
    public int getID_CARGO(){
        return ID_CARGO;
    }
    public void setID_CARGO(int number){
        this.ID_CARGO = number;
    }
    public String getTextlblUsuario(){
        return lblUsuario.getText();
    }
    public void setTextlblUsuario(String txt){
       lblUsuario.setText(txt);
    }
    public String getTextlblCargo(){
        return lblCargo.getText();
    }
    public void setTextlblCargo(String txt){
       lblCargo.setText(txt);
    }
    public void CentrarVentana(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }

    private void mni_Reg_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Reg_ProductosActionPerformed
        // TODO add your handling code here:
        RegistroProductos nuevo = new RegistroProductos();
        CentrarVentana(nuevo);

    }//GEN-LAST:event_mni_Reg_ProductosActionPerformed

    private void mni_Reg_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Reg_ClientesActionPerformed
        // TODO add your handling code here:
        RegistroClientes neww = new RegistroClientes();
        CentrarVentana(neww);
    }//GEN-LAST:event_mni_Reg_ClientesActionPerformed

    private void mni_Reg_CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Reg_CategoriasActionPerformed
        // TODO add your handling code here:
        RegistroCategoria nuevo = new RegistroCategoria();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Reg_CategoriasActionPerformed

    private void mni_Reg_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Reg_marcasActionPerformed
        // TODO add your handling code here:
        RegistroMarca nuevo = new RegistroMarca();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Reg_marcasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        RegistroTipoCondicion nuevo = new RegistroTipoCondicion();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        RegistroTipoComprobante nuevo = new RegistroTipoComprobante();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        RegistroTipoPago nuevo = new RegistroTipoPago();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        RegistroUsuarios nuevo = new RegistroUsuarios();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void mni_Mov_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Mov_ComprasActionPerformed
        // TODO add your handling code here:
        frmIngreso nuevo = new frmIngreso();
        nuevo.setID_USUARIO(ID_USUARIO);
        CentrarVentana(nuevo);
        
    }//GEN-LAST:event_mni_Mov_ComprasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmVentas nuevo = new frmVentas();
        nuevo.setlblVendedor(lblUsuario.getText());
        nuevo.setID_vendedor(ID_USUARIO);
        nuevo.setId_venta(0);
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mni_Cons_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Cons_VentasActionPerformed
        // TODO add your handling code here:
        RegistrosVentas nuevo = new RegistrosVentas();
        nuevo.setId_vendedor(ID_USUARIO);
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Cons_VentasActionPerformed

    private void mni_Reg_CorrelativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Reg_CorrelativosActionPerformed
        // TODO add your handling code here:
        Correlativos nuevo = new Correlativos();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Reg_CorrelativosActionPerformed

    private void mni_Mov_TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Mov_TransferenciaActionPerformed
        // TODO add your handling code here:
        frmTransferencia nuevo = new frmTransferencia();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Mov_TransferenciaActionPerformed

    private void mni_Mov_RASTREARPRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Mov_RASTREARPRODUCTOActionPerformed
        // TODO add your handling code here:
        LugarDeProducto nuevo = new LugarDeProducto();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Mov_RASTREARPRODUCTOActionPerformed

    private void mnu_MovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_MovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnu_MovimientosActionPerformed

    private void mni_Cons_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Cons_ProductosActionPerformed
        // TODO add your handling code here:
        frmLista nuevo = new frmLista();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Cons_ProductosActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        frmReporteCobranza nuevo = new frmReporteCobranza();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void mni_Cons_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Cons_ComprasActionPerformed
        // TODO add your handling code here:
        RegistroCompras nuevo = new RegistroCompras();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Cons_ComprasActionPerformed

    private void mni_Cons_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Cons_UsuariosActionPerformed
        // TODO add your handling code here:
        frmUsuarios nuevo = new frmUsuarios();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Cons_UsuariosActionPerformed

    private void mni_Reg_Asociacion_SeudonimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_Reg_Asociacion_SeudonimosActionPerformed
        // TODO add your handling code here:
        frmAsociacionPseudonimos nuevo = new frmAsociacionPseudonimos();
        CentrarVentana(nuevo);
    }//GEN-LAST:event_mni_Reg_Asociacion_SeudonimosActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mni_CerrarSesion;
    private javax.swing.JMenuItem mni_Cons_Compras;
    private javax.swing.JMenuItem mni_Cons_Productos;
    private javax.swing.JMenuItem mni_Cons_Usuarios;
    private javax.swing.JMenuItem mni_Cons_Ventas;
    private javax.swing.JMenuItem mni_Mov_Compras;
    private javax.swing.JMenuItem mni_Mov_RASTREARPRODUCTO;
    private javax.swing.JMenuItem mni_Mov_Transferencia;
    private javax.swing.JMenuItem mni_Reg_Asociacion_Seudonimos;
    private javax.swing.JMenuItem mni_Reg_Categorias;
    private javax.swing.JMenuItem mni_Reg_Clientes;
    private javax.swing.JMenuItem mni_Reg_Correlativos;
    private javax.swing.JMenuItem mni_Reg_Empleados;
    private javax.swing.JMenuItem mni_Reg_Productos;
    private javax.swing.JMenuItem mni_Reg_marcas;
    private javax.swing.JMenuItem mni_Salir;
    private javax.swing.JMenu mnu_Administrador;
    private javax.swing.JMenu mnu_Archivo;
    private javax.swing.JMenu mnu_Consultas;
    private javax.swing.JMenu mnu_Mov_Salidas;
    private javax.swing.JMenu mnu_Movimientos;
    private javax.swing.JMenu mnu_Registro;
    private javax.swing.JMenu mnu_Reportes;
    public static javax.swing.JDesktopPane tbn_escritorio;
    // End of variables declaration//GEN-END:variables
}
