/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;

import java.awt.event.KeyEvent;
import Utilitaries.Funcionalidades;
import Utilitaries.MetodoClientesProveedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import jtextfieldround.JTextFieldRound;

/**
 *
 * @author Paul
 */
public class RegistroClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form registroclientes
     */
    private int cantidadDigitosDocumento = 8; //por defecto en DNI
    private String tipoBusqueda = "DOCUMENTO";//Por defecto la busqueda por DNI
    //private String[] TipoDocumento = {"DNI","RUC","CARNET EXRANJERIA"};
    private int[] cantdigitosDocumento = {8, 11, 12, 12};

    public RegistroClientes() {
        initComponents();
        insertaconsulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtID = new jtextfieldround.JTextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNroIdentidad = new jtextfieldround.JTextFieldRound();
        txtNombreCompleto = new jtextfieldround.JTextFieldRound();
        txtContacto = new jtextfieldround.JTextFieldRound();
        txtDireccion = new jtextfieldround.JTextFieldRound();
        txtEmail = new jtextfieldround.JTextFieldRound();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBuscar = new jtextfieldround.JTextFieldRound();
        cbxPorDocumento = new javax.swing.JCheckBox();
        cbxPorNombre = new javax.swing.JCheckBox();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnbus = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 220, 220));
        setClosable(true);
        setIconifiable(true);

        jPanel2.setBackground(new java.awt.Color(33, 97, 140));
        jPanel2.setForeground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro de Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 274, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 273, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrincipal);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 12), new java.awt.Color(33, 97, 140))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        txtID.setEditable(false);

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 97, 140));
        jLabel1.setText("ID Cliente:");

        jLabel2.setBackground(new java.awt.Color(220, 220, 220));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 97, 140));
        jLabel2.setText("Tipo Documento:");

        jLabel4.setBackground(new java.awt.Color(220, 220, 220));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 97, 140));
        jLabel4.setText("Nro Identidad:");

        jLabel5.setBackground(new java.awt.Color(220, 220, 220));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 97, 140));
        jLabel5.setText("Nombre Completo:");

        jLabel6.setBackground(new java.awt.Color(220, 220, 220));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 97, 140));
        jLabel6.setText("Contacto:");

        jLabel7.setBackground(new java.awt.Color(220, 220, 220));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 97, 140));
        jLabel7.setText("Direccion:");

        jLabel8.setBackground(new java.awt.Color(220, 220, 220));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 97, 140));
        jLabel8.setText("Email:");

        txtNroIdentidad.setEditable(false);
        txtNroIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroIdentidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroIdentidadKeyTyped(evt);
            }
        });

        txtNombreCompleto.setEditable(false);

        txtContacto.setEditable(false);

        txtDireccion.setEditable(false);

        txtEmail.setEditable(false);

        cmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC", "PASAPORTE", "CARNET EXTRANJERIA" }));
        cmbTipoDocumento.setToolTipText("");
        cmbTipoDocumento.setPreferredSize(new java.awt.Dimension(250, 28));
        cmbTipoDocumento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoDocumentoItemStateChanged(evt);
            }
        });
        cmbTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNroIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNroIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(220, 220, 220));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 97, 140));
        jLabel9.setText("BUSCAR:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        cbxPorDocumento.setBackground(new java.awt.Color(220, 220, 220));
        cbxPorDocumento.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cbxPorDocumento.setForeground(new java.awt.Color(0, 0, 0));
        cbxPorDocumento.setSelected(true);
        cbxPorDocumento.setText("Por Documento");
        cbxPorDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPorDocumentoActionPerformed(evt);
            }
        });

        cbxPorNombre.setBackground(new java.awt.Color(220, 220, 220));
        cbxPorNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cbxPorNombre.setForeground(new java.awt.Color(0, 0, 0));
        cbxPorNombre.setText("Por Nombre");
        cbxPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPorNombreActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnbus.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnbus.setText("TODO");
        btnbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxPorDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxPorNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPorDocumento)
                    .addComponent(cbxPorNombre)
                    .addComponent(btnbus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        txtID.setText("");
        txtNroIdentidad.setText("");
        txtNombreCompleto.setText("");
        txtContacto.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtBuscar.setText("");
    }

    private void PermitirNuevoIngreso(boolean flag) {
        limpiar();
        txtID.setEditable(flag);
        txtNroIdentidad.setEditable(flag);
        txtNombreCompleto.setEditable(flag);
        txtContacto.setEditable(flag);
        txtDireccion.setEditable(flag);
        txtEmail.setEditable(flag);
    }

    private void insertaconsulta() {
        if (tipoBusqueda == "DOCUMENTO") {
            tblPrincipal.setModel(MetodoClientesProveedor.BuscarPorDocumento(txtBuscar.getText()));
        } else if (tipoBusqueda == "NOMBRE") {
            tblPrincipal.setModel(MetodoClientesProveedor.BuscarPorNombre(txtBuscar.getText()));
        }

    }
    public static boolean isTextFieldNotEmpty(JTextFieldRound textField) {
        // Obtener el texto del JTextField
        String texto = textField.getText().trim();
        return !texto.isEmpty();
    }

    private void cbxPorDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPorDocumentoActionPerformed
        // TODO add your handling code here:
        tipoBusqueda = "DOCUMENTO";
        cbxPorNombre.setSelected(false);
        if (cbxPorDocumento.isSelected()) {
            txtBuscar.setText("");

        } else {
            cbxPorDocumento.setSelected(true);
        }
    }//GEN-LAST:event_cbxPorDocumentoActionPerformed

    private void cbxPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPorNombreActionPerformed
        // TODO add your handling code here:
        tipoBusqueda = "NOMBRE";
        cbxPorDocumento.setSelected(false);
        if (cbxPorNombre.isSelected()) {
            txtBuscar.setText("");

        } else {
            cbxPorNombre.setSelected(true);
        }
    }//GEN-LAST:event_cbxPorNombreActionPerformed

    private void cmbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDocumentoActionPerformed
        // TODO add your handling code here:
        limpiar();
        /*if(cmbTipoDocumento.getSelectedItem() == "CARNET EXTRANJERIA") cantidadDigitosDocumento = 12;
        if(cmbTipoDocumento.getSelectedItem() == "RUC") cantidadDigitosDocumento = 11;
        if(cmbTipoDocumento.getSelectedItem() == "DNI") cantidadDigitosDocumento = 8;*/
        int index = cmbTipoDocumento.getSelectedIndex();
        cantidadDigitosDocumento = cantdigitosDocumento[index];

    }//GEN-LAST:event_cmbTipoDocumentoActionPerformed

    private void txtNroIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroIdentidadKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) || txtNroIdentidad.getText().length() >= cantidadDigitosDocumento) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNroIdentidadKeyTyped

    private void txtNroIdentidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroIdentidadKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(null, "Entro condicional");
            String TipoDocumento = cmbTipoDocumento.getSelectedItem().toString().toLowerCase();
            String NroDocumento = txtNroIdentidad.getText();
            String[] RespuestaAPI = Funcionalidades.ConsumoAPI2(TipoDocumento, NroDocumento);
            if (TipoDocumento.equals("dni")) {
                txtNombreCompleto.setText(RespuestaAPI[0] + " " + RespuestaAPI[1] + " " + RespuestaAPI[2]);
            }
            if(TipoDocumento.equals("ruc")){
                txtNombreCompleto.setText(RespuestaAPI[0]);
                txtDireccion.setText(RespuestaAPI[1]);
            }
        }
    }//GEN-LAST:event_txtNroIdentidadKeyPressed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && tipoBusqueda == "DOCUMENTO") {
            evt.consume();
        }
        if (!Character.isLetter(evt.getKeyChar()) && evt.getKeyChar() != ' ' && tipoBusqueda == "NOMBRE") {
            evt.consume();
        }

    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            insertaconsulta();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void cmbTipoDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoDocumentoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbTipoDocumentoItemStateChanged

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        PermitirNuevoIngreso(true);
        txtNroIdentidad.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //--------------------------------------------------
        if (isTextFieldNotEmpty(txtNroIdentidad)
                && isTextFieldNotEmpty(txtNombreCompleto)) {
            /*
                DNI  1
                RUC  6
                PASAPORTE  7
                CARNET EXTRANJERIA  4
            */
            int tipoidentidad = 1;
            switch (cmbTipoDocumento.getSelectedIndex()) {
                case 0: tipoidentidad = 1; 
                    break;
                case 1: tipoidentidad = 6; 
                    break;
                case 2: tipoidentidad = 7; 
                    break;
                case 3: tipoidentidad = 4; 
                    break;
                default:
                    throw new AssertionError();
            }
            MetodoClientesProveedor.InsertarCliente(tipoidentidad ,
                    txtNroIdentidad.getText(), txtNombreCompleto.getText(),
                    txtContacto.getText(), txtDireccion.getText(), txtEmail.getText());
            btnbusActionPerformed(evt);
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Faltan Datos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblPrincipal.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Si hay una fila seleccionada, muestra un JOptionPane con el índice de la fila
            int id = (int) tblPrincipal.getValueAt(filaSeleccionada, 0);
            String cliente = (String) tblPrincipal.getValueAt(filaSeleccionada, 3);
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea ELIMINAR este CLIENTE: " + cliente + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                MetodoClientesProveedor.EliminarCliente(id);
                btnbusActionPerformed(evt);
            }
        } else {
            // Si no hay ninguna fila seleccionada, muestra un mensaje indicando eso
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        PermitirNuevoIngreso(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusActionPerformed
        // TODO add your handling code here:
        insertaconsulta();
    }//GEN-LAST:event_btnbusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnbus;
    private javax.swing.JCheckBox cbxPorDocumento;
    private javax.swing.JCheckBox cbxPorNombre;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrincipal;
    private jtextfieldround.JTextFieldRound txtBuscar;
    private jtextfieldround.JTextFieldRound txtContacto;
    private jtextfieldround.JTextFieldRound txtDireccion;
    private jtextfieldround.JTextFieldRound txtEmail;
    private jtextfieldround.JTextFieldRound txtID;
    private jtextfieldround.JTextFieldRound txtNombreCompleto;
    private jtextfieldround.JTextFieldRound txtNroIdentidad;
    // End of variables declaration//GEN-END:variables
}
