/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frames;
import ConexionMysql.queries;
import Frames.BuscarCategoria;
import Frames.BuscarMarca;
import Utilitaries.Funcionalidades;
import Utilitaries.MetodoCategorias;
import Utilitaries.MetodoMarcas;
import Utilitaries.Producto;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Paul
 */
public class RegistroProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form registro
     */
    private static byte[] imagen;
    private static ArrayList<Object> ids_subcategorias = new ArrayList<Object>();
    private static ArrayList<Object> ids_categoriamarca = new ArrayList<Object>();
    private static int Id_Marca;
    private static int Id_Categoria;
    private static int id_producto = 0;
    public RegistroProductos() {
        /*
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistroProductos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(RegistroProductos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(RegistroProductos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(RegistroProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_buscarCategoria = new javax.swing.JButton();
        btn_BuscarMarca = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPad_Interno = new javax.swing.JTextField();
        txt_Modelo = new javax.swing.JTextField();
        txt_Precio = new javax.swing.JTextField();
        txt_GarantiaTotal = new javax.swing.JTextField();
        txt_GarantiaCliente = new javax.swing.JTextField();
        cmbSubcategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbCategoriaMarca = new javax.swing.JComboBox<>();
        txtCodigoFabricante = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btn_BuscarProducto = new javax.swing.JButton();
        btn_GuardarProducto = new javax.swing.JButton();
        btn_EliminarProducto = new javax.swing.JButton();
        btn_Regresar = new javax.swing.JButton();
        btnModificar3 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1011, 435));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1011, 435));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Categoria:");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SubCategoria:");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Pad-Interno:");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio:");

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txaDescripcion);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Garantia-Total:");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Garantia-cliente:");

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descripcion:");

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Modelo:");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Categoria-Marca:");

        btn_buscarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_lupa_desactivada.png"))); // NOI18N
        btn_buscarCategoria.setBorder(null);
        btn_buscarCategoria.setBorderPainted(false);
        btn_buscarCategoria.setContentAreaFilled(false);
        btn_buscarCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_lupa_activo.png"))); // NOI18N
        btn_buscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCategoriaActionPerformed(evt);
            }
        });

        btn_BuscarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_lupa_desactivada.png"))); // NOI18N
        btn_BuscarMarca.setBorder(null);
        btn_BuscarMarca.setBorderPainted(false);
        btn_BuscarMarca.setContentAreaFilled(false);
        btn_BuscarMarca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_lupa_activo.png"))); // NOI18N
        btn_BuscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarMarcaActionPerformed(evt);
            }
        });

        txtCategoria.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCategoria.setEnabled(false);

        txtMarca.setEditable(false);
        txtMarca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txtPad_Interno.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txt_Modelo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txt_Precio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txt_GarantiaTotal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txt_GarantiaCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        cmbSubcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO DETERMINADO", "ESCOJE CATEGORIA" }));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Marca:");

        cmbCategoriaMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO DETERMINADO", "ESCOJE CATEGORIA" }));

        txtCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Codigo Fabricante:");

        jButton1.setText("INSERTAR IMAGEN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblImagen.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(0, 0, 0));

        btn_BuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_buscar_desactivado_model2.png"))); // NOI18N
        btn_BuscarProducto.setBorder(null);
        btn_BuscarProducto.setBorderPainted(false);
        btn_BuscarProducto.setContentAreaFilled(false);
        btn_BuscarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_buscar_activo_model2.png"))); // NOI18N
        btn_BuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarProductoActionPerformed(evt);
            }
        });

        btn_GuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_guardar_desactivado_model2.png"))); // NOI18N
        btn_GuardarProducto.setBorder(null);
        btn_GuardarProducto.setBorderPainted(false);
        btn_GuardarProducto.setContentAreaFilled(false);
        btn_GuardarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_guardar_activo.png"))); // NOI18N
        btn_GuardarProducto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_guardar_activo.png"))); // NOI18N
        btn_GuardarProducto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_guardar_activo.png"))); // NOI18N
        btn_GuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarProductoActionPerformed(evt);
            }
        });

        btn_EliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_eliminar_desactivado_model1.png"))); // NOI18N
        btn_EliminarProducto.setBorder(null);
        btn_EliminarProducto.setBorderPainted(false);
        btn_EliminarProducto.setContentAreaFilled(false);
        btn_EliminarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_eliminar_activo_model1.png"))); // NOI18N
        btn_EliminarProducto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_eliminar_activo_model1.png"))); // NOI18N
        btn_EliminarProducto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_eliminar_activo_model1.png"))); // NOI18N

        btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_regresar_desactivado_model1.png"))); // NOI18N
        btn_Regresar.setBorder(null);
        btn_Regresar.setBorderPainted(false);
        btn_Regresar.setContentAreaFilled(false);
        btn_Regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_regresar_activo_model1.png"))); // NOI18N
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        btnModificar3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_modificar_desactivo.png"))); // NOI18N
        btnModificar3.setBorder(null);
        btnModificar3.setContentAreaFilled(false);
        btnModificar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar3.setFocusPainted(false);
        btnModificar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btn_modificar_activo.png"))); // NOI18N
        btnModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCategoriaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPad_Interno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImagen))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_buscarCategoria)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_BuscarMarca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_GarantiaCliente)
                                    .addComponent(txt_GarantiaTotal)
                                    .addComponent(txt_Precio)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_BuscarProducto)
                        .addGap(14, 14, 14)
                        .addComponent(btn_GuardarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_EliminarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Regresar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(btn_buscarCategoria)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_GarantiaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_GarantiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPad_Interno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_BuscarMarca)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbCategoriaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_GuardarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_BuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_EliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_buscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCategoriaActionPerformed
        // TODO add your handling code here:
        BuscarCategoria nuevo = new BuscarCategoria();
        Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
    }//GEN-LAST:event_btn_buscarCategoriaActionPerformed

    private void btn_BuscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarMarcaActionPerformed
        // TODO add your handling code here:
        BuscarMarca nuevo = new BuscarMarca();
        Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
    }//GEN-LAST:event_btn_BuscarMarcaActionPerformed
    private void Limpiar(){
        txtCategoria.setText(null);
        txtMarca.setText(null);
        txtPad_Interno.setText(null);
        txt_Modelo.setText(null);
        txtCodigoFabricante.setText(null);
        txt_Precio.setText(null);
        txt_GarantiaTotal.setText(null);
        txt_GarantiaCliente.setText(null);
        txaDescripcion.setText(null);
        lblImagen.setIcon(null);
    }
    private boolean VerificarContenido(){
        boolean rpta = false;
        rpta = txtCategoria.getText() != null && txtMarca.getText() != null && txtPad_Interno.getText() != null &&
               txt_Modelo.getText() != null && txtCodigoFabricante.getText() != null && txt_Precio.getText() != null &&
               txt_GarantiaTotal.getText() != null && txt_GarantiaCliente.getText() != null && txaDescripcion.getText() != null;
        if(!rpta){
            JOptionPane.showMessageDialog(null, "ALGUNO DE LOS CAMPOS NO ESTAN COMPLETOS");
        }
        return rpta;
    }
    private void btn_GuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarProductoActionPerformed
        // TODO add your handling code here:
        boolean flag = VerificarContenido();
        if(flag){
            Producto nuevo = new Producto();
            nuevo.setId_marca(Id_Marca);
            nuevo.setId_categoria((int)ids_categoriamarca.get(cmbCategoriaMarca.getSelectedIndex()));
            nuevo.setId_subcategoria((int)ids_subcategorias.get(cmbSubcategoria.getSelectedIndex()));
            nuevo.setPad_interno(txtPad_Interno.getText());
            nuevo.setModelo(txt_Modelo.getText());
            nuevo.setCodigofabricante(txtCodigoFabricante.getText());
            nuevo.setDescripcion(txaDescripcion.getText());
            nuevo.setPrecio(Double.parseDouble(txt_Precio.getText()));
            nuevo.setStock(0);
            nuevo.setImagen(imagen);
            nuevo.setGarantia_cliente(Integer.parseInt(txt_GarantiaCliente.getText()));
            nuevo.setGarantia_total(Integer.parseInt(txt_GarantiaTotal.getText()));
            nuevo.InsertarNuevoProductoDataBase();
            Limpiar();
        }
        
    }//GEN-LAST:event_btn_GuardarProductoActionPerformed
    private static void mostrarImagen() {
        try {
            int anchoDeseado = 200;
            // Cargar la imagen desde los datos binarios
            BufferedImage bufferedImage = ImageIO.read(new ByteArrayInputStream(imagen));

            // Calcular la proporción para redimensionar la imagen
            double proporcion = (double) anchoDeseado / bufferedImage.getWidth();
            int altoDeseado = (int) (bufferedImage.getHeight() * proporcion);

            // Escalar la imagen
            Image imagenEscalada = bufferedImage.getScaledInstance(anchoDeseado, altoDeseado, Image.SCALE_SMOOTH);

            // Establecer la imagen en el JLabel
            lblImagen.setIcon(new ImageIcon(imagenEscalada));
            
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al mostrar la imagen.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private byte[] leerDatosImagen(File archivoImagen) {
        try (FileInputStream fis = new FileInputStream(archivoImagen)) {
            byte[] buffer = new byte[(int) archivoImagen.length()];
            fis.read(buffer);
            return buffer;
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //FileSystem fileChooser = FileSystems.getDefault();
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(null);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoImagen = fileChooser.getSelectedFile();
            imagen = leerDatosImagen(archivoImagen);
            if (imagen != null) {
                mostrarImagen();
                setSize(1011, 620);
                JOptionPane.showMessageDialog(null, "Imagen insertada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al leer la imagen.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
    public static void insertarDatos(){
        if(id_producto != 0){
            Producto nuevo = new Producto(id_producto);
            cmbSubcategoria.removeAllItems();
            cmbCategoriaMarca.removeAllItems();
            ids_subcategorias.clear();
            ids_categoriamarca.clear();
            try{
                for(Object[] item : MetodoCategorias.SubCategoriasAsociadaConIDSubcategoria(nuevo.getId_subcategoria())){
                    ids_subcategorias.add(item[0]);
                    cmbSubcategoria.addItem(item[1].toString());
                }
                for(Object[] item : MetodoMarcas.SubCategoriaMarcaAsociada(nuevo.getId_marca())){
                    ids_categoriamarca.add(item[0]);
                    cmbCategoriaMarca.addItem(item[1].toString());
                }
                cmbSubcategoria.setSelectedIndex(ids_subcategorias.indexOf(nuevo.getId_subcategoria()));
                cmbCategoriaMarca.setSelectedIndex(ids_categoriamarca.indexOf(nuevo.getId_marca()));
            }catch(Exception e){
                System.out.println(e);
            }
            txtCategoria.setText(nuevo.NombreCategoria());
            Id_Marca = nuevo.getId_marca();
            txtMarca.setText(nuevo.NombreMarca());
            txtPad_Interno.setText(nuevo.getPad_interno());
            txt_Modelo.setText(nuevo.getModelo());
            txtCodigoFabricante.setText(nuevo.getCodigofabricante());
            txt_Precio.setText(nuevo.getPrecio() + "");
            txt_GarantiaTotal.setText(nuevo.getGarantia_total() + "");
            txt_GarantiaCliente.setText(nuevo.getGarantia_cliente() + "");
            txaDescripcion.setText(nuevo.getDescripcion());
            nuevo.CargaImagen();
            imagen = nuevo.getImagen();
            if(imagen != null){
                mostrarImagen();
            }
            
        }
    }
    private void btn_BuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarProductoActionPerformed
        // TODO add your handling code here:
        BuscarProducto nuevo = new BuscarProducto();
        nuevo.setFrmAIndexar(4);
        Funcionalidades.CentrarVentana(frmPrincipal.tbn_escritorio, nuevo);
        setSize(1011, 620);
    }//GEN-LAST:event_btn_BuscarProductoActionPerformed

    private void btnModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar3ActionPerformed
        // TODO add your handling code here:
        boolean flag = VerificarContenido();
        if(flag && id_producto != 0){
            Producto nuevo = new Producto(id_producto);
            nuevo.setId_marca(Id_Marca);
            nuevo.setId_categoria((int)ids_categoriamarca.get(cmbCategoriaMarca.getSelectedIndex()));
            nuevo.setId_subcategoria((int)ids_subcategorias.get(cmbSubcategoria.getSelectedIndex()));
            nuevo.setModelo(txt_Modelo.getText());
            nuevo.setCodigofabricante(txtCodigoFabricante.getText());
            nuevo.setDescripcion(txaDescripcion.getText());
            nuevo.setPrecio(Double.parseDouble(txt_Precio.getText()));
            nuevo.setStock(0);
            nuevo.setImagen(imagen);
            nuevo.setGarantia_cliente(Integer.parseInt(txt_GarantiaCliente.getText()));
            nuevo.setGarantia_total(Integer.parseInt(txt_GarantiaTotal.getText()));
            nuevo.ActualizarProductoDatabase();
            Limpiar();
        }
    }//GEN-LAST:event_btnModificar3ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnModificar3;
    private javax.swing.JButton btn_BuscarMarca;
    private javax.swing.JButton btn_BuscarProducto;
    private javax.swing.JButton btn_EliminarProducto;
    private javax.swing.JButton btn_GuardarProducto;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_buscarCategoria;
    public static javax.swing.JComboBox<String> cmbCategoriaMarca;
    public static javax.swing.JComboBox<String> cmbSubcategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lblImagen;
    private static javax.swing.JTextArea txaDescripcion;
    public static javax.swing.JTextField txtCategoria;
    private static javax.swing.JTextField txtCodigoFabricante;
    public static javax.swing.JTextField txtMarca;
    private static javax.swing.JTextField txtPad_Interno;
    private static javax.swing.JTextField txt_GarantiaCliente;
    private static javax.swing.JTextField txt_GarantiaTotal;
    private static javax.swing.JTextField txt_Modelo;
    private static javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Id_Marca
     */
    public static int getId_Marca() {
        return Id_Marca;
    }

    /**
     * @param aId_Marca the Id_Marca to set
     */
    public static void setId_Marca(int aId_Marca) {
        Id_Marca = aId_Marca;
    }

    /**
     * @return the Id_Categoria
     */
    public static int getId_Categoria() {
        return Id_Categoria;
    }

    /**
     * @param aId_Categoria the Id_Categoria to set
     */
    public static void setId_Categoria(int aId_Categoria) {
        Id_Categoria = aId_Categoria;
    }

    /**
     * @return the id_producto
     */
    public static int getId_producto() {
        return id_producto;
    }

    /**
     * @param aId_producto the id_producto to set
     */
    public static void setId_producto(int aId_producto) {
        id_producto = aId_producto;
    }

    /**
     * @return the ids_subcategorias
     */
    public static ArrayList<Object> getIds_subcategorias() {
        return ids_subcategorias;
    }

    /**
     * @param aIds_subcategorias the ids_subcategorias to set
     */
    public static void setIds_subcategorias(ArrayList<Object> aIds_subcategorias) {
        ids_subcategorias = aIds_subcategorias;
    }

    /**
     * @return the ids_categoriamarca
     */
    public static ArrayList<Object> getIds_categoriamarca() {
        return ids_categoriamarca;
    }

    /**
     * @param aIds_categoriamarca the ids_categoriamarca to set
     */
    public static void setIds_categoriamarca(ArrayList<Object> aIds_categoriamarca) {
        ids_categoriamarca = aIds_categoriamarca;
    }


}
